# Site settings
title: DaedaFusion
email: mark.philpot@gmail.com
url: https://daedafusion.com
description: "DaedaFusion :: plugable component architectures"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: DaedaFusion

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mark_philpot
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url:
  - title: github
    url: https://github.com/daedafusion

# Build settings
markdown: kramdown
permalink: pretty
